initialStates = {
 'Acre': 'AC',
 'Alagoas': 'AL',
 'Amapa': 'AP',
 'Amazonas': 'AM',
 'Bahia': 'BA',
 'Ceara': 'CE',
 'Distrito Federal': 'DF',
 'Espirito Santo': 'ES',
 'Goias': 'GO',
 'Maranhao': 'MA',
 'Mato Grosso': 'MT',
 'Mato Grosso do Sul': 'MS',
 'Minas Gerais': 'MG',
 'Para': 'PA',
 'Paraiba': 'PB',
 'Parana': 'PR',
 'Pernambuco': 'PE',
 'Piaui': 'PI',
 'Rio de Janeiro': 'RJ',
 'Rio Grande do Norte': 'RN',
 'Rio Grande do Sul': 'RS',
 'Rondonia': 'RO',
 'Roraima': 'RR',
 'Santa Catarina': 'SC',
 'Sao Paulo': 'SP',
 'Sergipe': 'SE',
 'Tocantins': 'TO'
}