initialStates = {
 'Acre': 'AC',
 'Alagoas': 'AL',
 'Amapa': 'AP',
 'Amazonas': 'AM',
 'Bahia': 'BA',
 'Ceara': 'CE',
 'Distrito Federal': 'DF',
 'Espirito Santo': 'ES',
 'Goias': 'GO',
 'Maranhao': 'MA',
 'Mato Grosso': 'MT',
 'Mato Grosso do Sul': 'MS',
 'Minas Gerais': 'MG',
 'Para': 'PA',
 'Paraiba': 'PB',
 'Parana': 'PR',
 'Pernambuco': 'PE',
 'Piaui': 'PI',
 'Rio de Janeiro': 'RJ',
 'Rio Grande do Norte': 'RN',
 'Rio Grande do Sul': 'RS',
 'Rondonia': 'RO',
 'Roraima': 'RR',
 'Santa Catarina': 'SC',
 'Sao Paulo': 'SP',
 'Sergipe': 'SE',
 'Tocantins': 'TO'
}

initialsToState = {
    'AC': 'Acre',
    'AL': 'Alagoas',
    'AP': 'Amapa',
    'AM': 'Amazonas',
    'BA': 'Bahia',
    'CE': 'Ceara',
    'DF': 'Distrito Federal',
    'ES': 'Espirito Santo',
    'GO': 'Goias',
    'MA': 'Maranhao',
    'MT': 'Mato Grosso',
    'MS': 'Mato Grosso do Sul',
    'MG': 'Minas Gerais',
    'PA': 'Para',
    'PB': 'Paraiba',
    'PR': 'Parana',
    'PE': 'Pernambuco',
    'PI': 'Piaui',
    'RJ': 'Rio de Janeiro',
    'RN': 'Rio Grande do Norte',
    'RS': 'Rio Grande do Sul',
    'RO': 'Rondonia',
    'RR': 'Roraima',
    'SC': 'Santa Catarina',
    'SP': 'Sao Paulo',
    'SE': 'Sergipe',
    'TO': 'Tocantins'
}